name: Test cache inputs

on: [push, pull_request]

jobs:
   test-pip-cache:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: priyagupta108/setup-python@test-pr-973
        with:
          python-version: '3.13.1t'
          cache: 'pip'
      - run: pip install -r requirements.txt

   test-poetry-cache:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry  
      - name: Update Poetry lock file
        run: poetry lock  
      - name: Set up Python
        uses: priyagupta108/setup-python@test-pr-973
        with:
          python-version: '3.13.1t'
          cache: 'poetry'
      - run: poetry install --no-root
  
