name: Test 1079 for non cached versions

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  test-python-executables:
    strategy:
      matrix:
        os: [windows-latest]
        architecture: [x86, x64]

      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.8.1
            3.9.1
            3.10.1
            3.11.1
            3.12.1
            3.13.1
          architecture: ${{ matrix.architecture }}
      - name: Check for Python 3.8.1 .exe files
        shell: cmd
        run: |
          echo "Checking Python 3.8.1 .exe files for architecture ${{ matrix.architecture }}..."
          dir C:\hostedtoolcache\windows\Python\3.8.1\python-3.8.1*.exe /s /b
      - name: Check for Python 3.9.1 .exe files
        shell: cmd
        run: |
          echo "Checking Python 3.9.1 .exe files for architecture ${{ matrix.architecture }}..."
          dir C:\hostedtoolcache\windows\Python\3.9.1\python-3.9.1*.exe /s /b

      - name: Check for Python 3.10.1 .exe files
        shell: cmd
        run: |
          echo "Checking Python 3.10.1 .exe files for architecture ${{ matrix.architecture }}..."
          dir C:\hostedtoolcache\windows\Python\3.10.1\python-3.10.1*.exe /s /b

      - name: Check for Python 3.11.1 .exe files
        shell: cmd
        run: |
          echo "Checking Python 3.11.1 .exe files for architecture ${{ matrix.architecture }}..."
          dir C:\hostedtoolcache\windows\Python\3.11.1\python-3.11.1*.exe /s /b

      - name: Check for Python 3.12.1 .exe files
        shell: cmd
        run: |
          echo "Checking Python 3.12.1 .exe files for architecture ${{ matrix.architecture }}..."
          dir C:\hostedtoolcache\windows\Python\3.12.1\python-3.12.1*.exe /s /b

      - name: Check for Python 3.13.1 .exe files
        shell: cmd
        run: |
          echo "Checking Python 3.13.1 .exe files for architecture ${{ matrix.architecture }}..."
          dir C:\hostedtoolcache\windows\Python\3.13.1\python-3.13.1*.exe /s /b
